#Home 首页
title: 鹿鹿有为
background: none

#侧滑栏
lists:
  - title: 我的主页
    url: /index.html
  - title: 归档记录
    url: /achieve.html
  - title: 哈哈
    url: /d

footer:
    text: 鹿鹿有为©2022-2022 新备案号：-