#！测试版本 未开发完成 Bete version , havnt developed completly. 

#Home 首页  

#title: Topbar text 顶栏文本
#background: Background image 背景图片
title: 鹿鹿有为
background: https://pic.imgdb.cn/item/65bca7cd871b83018a0605b8.png

defaultimg: https://pic.imgdb.cn/item/65913386c458853aefb5f79a.jpg

#Nearbar 侧滑栏
lists:
  - title: 我的主页
    url: /index.html
  - title: 归档记录
    url: /achieve.html
  - title: 哈哈
    url: /d

#Footer Text 页尾附加文本
footer:
    text: 鹿鹿有为©2022-2022 
