#！测试版本 未开发完成 Bete version , havnt developed completly. 

#Home 首页  

#title: Topbar text 顶栏文本
#background: Background image 背景图片
title: 鹿鹿有为
background: https://tuchuang.voooe.cn/images/2023/05/22/00-45-7519843a-957e-4e9a-89ae-adea78b7c8ccdb1c29a3-1738-41b7-b2c4-a09c2cc95f1b.jpg

defaultimg: https://tuchuang.voooe.cn/images/2023/05/22/00-49-7519843a-957e-4e9a-89ae-adea78b7c8cc49b79ecf-c948-4c9f-8062-47a111626229.jpg

#Nearbar 侧滑栏
lists:
  - title: 我的主页
    url: /index.html
  - title: 归档记录
    url: /achieve.html
  - title: 哈哈
    url: /d

#Footer Text 页尾附加文本
footer:
    text: 鹿鹿有为©2022-2022 
